version: '3'

services:
  web:
    build: .
    ports:
      - "9090:9090"
    environment:
      REDIS_URL: redis:6379
    depends_on:
      - redis
  redis:
    image: "redis"
    ports:
      - "6379"
